version: 2
updates:
  # Enable version updates for Go
  - package-ecosystem: "gomod"
    # Look for `go.mod` and `go.sum` files in the `root` directory
    directory: "/"
    # Check for updates every day (weekdays)
    schedule:
      interval: "daily"